// lib/firebase_options.dart
// Ce fichier contient la configuration Firebase pour l'application.
// Il est généré automatiquement par la CLI Firebase et ne doit pas être modifié manuellement.

// File generated by the Firebase CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Ceci est temporaire, car je ne configure la configuration Web que pour le moment.
    // Vous pouvez ajouter des configurations pour d'autres plates-formes ici plus tard.
    throw UnsupportedError(
      'DefaultFirebaseOptions n\'a pas été configuré pour cette plateforme - '
      'vous pouvez les générer avec la CLI FlutterFire',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCyp1nSRKoKO69ioWy5a8FPUkOAPEGhFRU",
    appId: "1:775251936276:web:66d8ffc2e1f26347e01301",
    messagingSenderId: "775251936276",
    projectId: "evaluation-d947b",
    authDomain: "evaluation-d947b.firebaseapp.com",
    storageBucket: "evaluation-d947b.appspot.com",
    measurementId: "G-E9GMHZ27GM",
  );
}
